### ISSUE TITLE
Is Docker image Available?

### ISSUE THREAD

**Issue by mariushosting** [dani3l0/honey#1]
Nice project! Congrats!
Is Docker image available?

**Comment by dani3l0** [comment]
Not yet, but many people suggested to add it, so Docker image is on the way :)

**Comment by mariushosting** [comment]
> Not yet, but many people suggested to add it, so Docker image is on the way :)

Awesome Thank You!

**Comment by dani3l0** [comment]
**We have a Dockerfile (#2)**

but not closing this issue yet as we have kinda no options for configuration and we are not using Vite's built-in production webserver

**Comment by dani3l0** [comment]
**Project seems to run fine under Docker** with the command provided in README.

For configuration, please use bind mount of `config` directory. Environment variables turned out to be are kinda inappropriate in terms of adding custom services.

Ofc, if you have any problems, ideas or questions, feel free to open another issues :)
