### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by ghost** [dani3l0/honey#3]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

any plans on arm support? it's the most beautiful dashboard i've ever seen :(

**Comment by dani3l0** [comment]
Hey, I'm glad u like the dashboard

I guess the problem is related to **GitHub Workflows** and poor setup I've done. For now, you can either try to deploy via provided Dockerfile or host it bare-metal (by putting assets on some webserver).
But yes, arm support is essential as so many people run small homeservers on RaspberryPis and other devices.

I will try to update GitHub Workflows file to build images for other arches as well.

Thanks for opening the issue!

**Comment by dani3l0** [comment]
Seems like it works? I guess you can even pull the image without sha hash
![image](https://github.com/dani3l0/honey/assets/111448519/a4102ca6-b3b9-4855-8390-feeaf5baae15)

However, I didn't manage to build armv7 image because GitHub Actions worker somehow just hanged on `npm install` (at least for 10 minutes)

Lemme know if it works for you

**Comment by dani3l0** [comment]
Arm support is done.

Feel free to reopen if there are any further issues related to this topic.
